apiVersion: v1
kind: Namespace
metadata:
  name:  test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
  namespace: test
  labels:
    app: nginx-hello
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
      - name: nginx-hello
        image: nginxdemos/hello
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-hello-service
  namespace: test
spec:
  selector:
    app: nginx-hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: LoadBalancer