apiVersion: v1
kind: Namespace
metadata:
  name:  test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: la-store
  namespace: test
  labels:
    app: la-store
spec:
  replicas: 4
  selector:
    matchLabels:
      app: la-store
  template:
    metadata:
      labels:
        app: la-store
    spec:
      containers:
      - name: la-store
        image: linuxacademycontent/store-products:1.0.0
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: la-store-service
  namespace: test
spec:
  selector:
    app: la-store
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort